# Generated by Django 2.2 on 2020-07-22 08:46

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20200722_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(default='as'),
            preserve_default=False,
        ),
    ]
