# Generated by Django 2.2 on 2020-07-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_auto_20200722_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='profiles', to='twitter.Following'),
        ),
    ]
