# Generated by Django 2.2 on 2020-07-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('Leave_ID', models.CharField(default=' ', max_length=5, primary_key=True, serialize=False)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'december')], max_length=10)),
                ('Employee_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Customer')),
            ],
        ),
    ]
