# Generated by Django 2.2 on 2020-07-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profilephoto_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilephoto',
        ),
        migrations.DeleteModel(
            name='username',
        ),
    ]
