# Generated by Django 2.2 on 2020-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0005_auto_20200724_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rule',
            field=models.IntegerField(choices=[(0, '0%'), (5, '5%'), (8, '8%'), (23, '23%')], default=23),
        ),
    ]
