# Generated by Django 2.2 on 2020-07-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0006_product_vat_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_rule',
        ),
    ]
