# Generated by Django 2.2 on 2020-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0008_auto_20200818_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsInsightsHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=32, null=True)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
