# Generated by Django 2.2 on 2020-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
