# Generated by Django 2.2 on 2020-10-21 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('child_contacts', models.ManyToManyField(blank=True, related_name='_contact_child_contacts_+', to='line_item.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('item_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item ID')),
                ('item_detail_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Detail ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_allowed', models.BooleanField(default=False)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('opportunity_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Opportunity ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('template_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Template ID')),
                ('purchase_type', models.CharField(blank=True, choices=[('perpetual', 'Perpetual'), ('monthly_subscription', 'Monthly Subscription')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.Itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.ChargeCategory')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.LineItem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='line_item.Template')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('discount_method', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', '%')], default='percentage', max_length=50)),
                ('monthlies_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('setup_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('upfront_deposit', models.CharField(blank=True, choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('other', 'Other'), ('amount', 'Amount')], max_length=50, null=True)),
                ('upfront_deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('balance_distribution', models.BooleanField(default=False)),
                ('balance_distribution_type', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=50, null=True)),
                ('amount_at_execution_of_contract', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('attention_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Contact')),
                ('contact_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='line_item.Contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Opportunity')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Template')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('item_discount', models.BooleanField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, default=1, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('charge_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.ChargeCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.LineItem')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.SaleProposal')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='line_item.Opportunity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.Template')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='line_item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.LineItemType'),
        ),
        migrations.CreateModel(
            name='ChargeCategoryDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('charge_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='line_item.ChargeCategory')),
                ('discount_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.DiscountOffer')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.SaleProposal')),
            ],
        ),
    ]
