# Generated by Django 2.2 on 2020-10-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('item_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item ID')),
                ('item_detail_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Detail ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_allowed', models.BooleanField(default=False)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='LineItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('opportunity_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Opportunity ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('template_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Template ID')),
                ('purchase_type', models.CharField(blank=True, choices=[('perpetual', 'Perpetual'), ('monthly_subscription', 'Monthly Subscription')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.LineItem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.Template')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.ChargeCategory')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.Opportunity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.Template')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='line_item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.LineItemType'),
        ),
    ]
