# Generated by Django 2.2 on 2020-10-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitytemplates',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='line_item.Opportunity'),
        ),
    ]
