# Generated by Django 2.2 on 2020-10-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0002_auto_20201006_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatelineitems',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='line_item.Template'),
        ),
    ]
