# Generated by Django 2.2 on 2020-10-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0003_auto_20201007_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('child_contacts', models.ManyToManyField(blank=True, related_name='_contact_child_contacts_+', to='line_item.Contact')),
            ],
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.CreateModel(
            name='SaleProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('discount_method', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', '%')], default='percentage', max_length=50)),
                ('monthlies_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('setup_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('upfront_deposit', models.CharField(blank=True, choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('other', 'Other'), ('amount', 'Amount')], max_length=50, null=True)),
                ('upfront_deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('balance_distribution', models.BooleanField(blank=True, null=True)),
                ('balance_distribution_type', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=50, null=True)),
                ('amount_at_execution_of_contract', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('attention_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Contact')),
                ('contact_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='line_item.Contact')),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Opportunity')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.Template')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('item_discount', models.BooleanField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('charge_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.ChargeCategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.LineItem')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.SaleProposal')),
            ],
        ),
    ]
