# Generated by Django 2.2 on 2020-10-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0005_auto_20201007_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitytemplates',
            name='charge_category',
        ),
        migrations.AddField(
            model_name='templatelineitems',
            name='charge_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_item.ChargeCategory'),
        ),
    ]
