# Generated by Django 2.2 on 2020-10-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0006_auto_20201008_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='name',
            field=models.CharField(default='new', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='line_item.SaleProposal'),
        ),
    ]
