# Generated by Django 2.2 on 2020-10-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0007_auto_20201009_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='name',
        ),
        migrations.AddField(
            model_name='saleproposal',
            name='name',
            field=models.CharField(default='New', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='line_item.SaleProposal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleproposal',
            name='contact_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='line_item.Contact'),
        ),
    ]
