# Generated by Django 2.2 on 2020-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0009_auto_20201012_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
